#!/bin/bash
#
# Run the dollars program using default values for host & port

declare -gr ADDR='0.0.0.0'
declare -gr PORT='9090'

make clean && make
if [[ -e dollars ]]; then
	chromium-browser "http://${ADDR}:${PORT}" &
	./dollars --docroot . --http-address "${ADDR}" --http-port "${PORT}"
else
	echo "dollars not built"
fi
